### ISSUE TITLE
hard coding run directory makes it less portable

### ISSUE THREAD

**Issue by mbyvcm** [AWGL/VirtualHood#9]
can the run directory be over-ridden when given as argument?

**Comment by mbyvcm** [comment]
https://github.com/AWGL/VirtualHood/blob/24cdec486e31c85acc481a412d08a8f846c1d7c3/panCancer_report.py#L1391

**Comment by mbyvcm** [comment]
Would it be possible to keep the current (viglen) path as default, but allow user to override with an path given as an argument?

**Comment by LauraMcCluskey7** [comment]
Resolved in version 1.3.0
